package harness

import (
	"testing"
	"time"

	"github.com/young1ll/keelage/internal/core"
)

var (
	t0    = time.Date(2026, 9, 10, 9, 0, 0, 0, time.UTC)
	human = core.ActorRef{Kind: core.ActorHuman, ID: "alice"}
	agent = core.ActorRef{Kind: core.ActorAgent, ID: "cc-1", Owner: "alice"}
	team  = core.ScopeKey{Org: "acme", Team: "core"}
	repo  = core.ScopeKey{Org: "acme", Team: "core", Repo: "acme/api"}
	prod  = core.ScopeKey{Org: "acme", Product: "pay"}
)

func dctx(actor core.ActorRef) core.DecideContext {
	return core.DecideContext{Now: t0, Actor: actor, Autonomy: core.L0, Cap: core.MaxLevel, Policy: core.DefaultPolicy()}
}

func code(t *testing.T, err error) string {
	t.Helper()
	if err == nil {
		return ""
	}
	r, ok := core.AsRejection(err)
	if !ok {
		t.Fatalf("not a rejection: %v", err)
	}
	return r.Code
}

func drafted(t *testing.T, authored bool) Constraint {
	t.Helper()
	cmd := DraftConstraint{ID: "c1", ConstraintKind: KindRule, Scope: repo, Body: "no retries", Authored: authored}
	if !authored {
		cmd.Origin = []core.ID{"j1"}
	}
	evs, err := (Constraint{}).Decide(cmd, dctx(human))
	if err != nil {
		t.Fatal(err)
	}
	return core.Replay(Constraint{}, evs)
}

func verified(t *testing.T, authored bool) Constraint {
	t.Helper()
	c := drafted(t, authored)
	evs, err := c.Decide(VerifyConstraint{NewConstraintCmd("c1", "")}, dctx(human))
	if err != nil {
		t.Fatal(err)
	}
	return core.Replay(c, evs)
}

func TestConstraint_Draft(t *testing.T) {
	base := DraftConstraint{ID: "c1", ConstraintKind: KindRule, Scope: repo, Body: "b", Authored: true}
	cases := []struct {
		name  string
		state Constraint
		mod   func(*DraftConstraint)
		ctx   core.DecideContext
		want  string
	}{
		{"authored ok", Constraint{}, func(*DraftConstraint) {}, dctx(human), ""},
		{"from judgments ok", Constraint{}, func(c *DraftConstraint) { c.Authored = false; c.Origin = []core.ID{"j1"} }, dctx(agent), ""},
		{"exists", Constraint{State: StateGenerated}, func(*DraftConstraint) {}, dctx(human), "exists"},
		{"no id", Constraint{}, func(c *DraftConstraint) { c.ID = "" }, dctx(human), "invalid"},
		{"bad kind", Constraint{}, func(c *DraftConstraint) { c.ConstraintKind = "x" }, dctx(human), "invalid"},
		{"bad scope", Constraint{}, func(c *DraftConstraint) { c.Scope = core.ScopeKey{PathGlob: "a/*"} }, dctx(human), "invalid"},
		{"empty body", Constraint{}, func(c *DraftConstraint) { c.Body = "" }, dctx(human), "invalid"},
		{"neither authored nor promoted", Constraint{}, func(c *DraftConstraint) { c.Authored = false }, dctx(human), "no-origin"},
		{"autonomy over cap", Constraint{}, func(c *DraftConstraint) { c.ConstraintKind = KindAutonomy; c.Level = core.L2 }, func() core.DecideContext { d := dctx(human); d.Cap = core.L1; return d }(), "over-cap"},
		{"autonomy at cap ok", Constraint{}, func(c *DraftConstraint) { c.ConstraintKind = KindAutonomy; c.Level = core.L1 }, func() core.DecideContext { d := dctx(human); d.Cap = core.L1; return d }(), ""},
		{"autonomy bad level", Constraint{}, func(c *DraftConstraint) { c.ConstraintKind = KindAutonomy; c.Level = 9 }, dctx(human), "invalid"},
	}
	for _, c := range cases {
		cmd := base
		c.mod(&cmd)
		evs, err := c.state.Decide(cmd, c.ctx)
		if got := code(t, err); got != c.want {
			t.Errorf("%s: got %q want %q (%v)", c.name, got, c.want, err)
			continue
		}
		if c.want == "" {
			s := core.Replay(Constraint{}, evs)
			if s.State != StateGenerated || s.ID != "c1" || s.Kind != cmd.ConstraintKind || s.Scope != repo {
				t.Errorf("%s: state after draft %+v", c.name, s)
			}
		}
	}
}

func TestConstraint_Verify(t *testing.T) {
	cases := []struct {
		name  string
		state Constraint
		actor core.ActorRef
		want  string
	}{
		{"generated by human", drafted(t, true), human, ""},
		{"agent", drafted(t, true), agent, "human-only"},
		{"already verified", verified(t, true), human, "bad-state"},
		{"retired", Constraint{ID: "c1", State: StateRetired}, human, "bad-state"},
		{"missing", Constraint{}, human, "not-found"},
	}
	for _, c := range cases {
		evs, err := c.state.Decide(VerifyConstraint{NewConstraintCmd("c1", "")}, dctx(c.actor))
		if got := code(t, err); got != c.want {
			t.Errorf("%s: got %q want %q", c.name, got, c.want)
		}
		if c.want == "" && core.Replay(c.state, evs).State != StateVerified {
			t.Errorf("%s: not verified", c.name)
		}
	}
}

func TestConstraint_Promote(t *testing.T) {
	ok := PromoteConstraint{ConstraintCmd: NewConstraintCmd("c1", ""), ToScope: team, Origin: []core.ID{"j1", "j2"}, Explanation: "same anchor rejected three times"}
	cases := []struct {
		name  string
		state Constraint
		mod   func(*PromoteConstraint)
		actor core.ActorRef
		want  string
	}{
		{"ok", verified(t, true), func(*PromoteConstraint) {}, human, ""},
		{"existing origin suffices", verified(t, false), func(p *PromoteConstraint) { p.Origin = nil }, human, ""},
		{"agent", verified(t, true), func(*PromoteConstraint) {}, agent, "human-only"},
		{"not verified", drafted(t, true), func(*PromoteConstraint) {}, human, "bad-state"},
		{"same scope", verified(t, true), func(p *PromoteConstraint) { p.ToScope = repo }, human, "not-wider"},
		{"narrower", verified(t, true), func(p *PromoteConstraint) {
			p.ToScope = core.ScopeKey{Org: "acme", Team: "core", Repo: "acme/api", PathGlob: "src/*"}
		}, human, "not-wider"},
		{"orthogonal", verified(t, true), func(p *PromoteConstraint) { p.ToScope = prod }, human, "not-wider"},
		{"no origin", verified(t, true), func(p *PromoteConstraint) { p.Origin = nil }, human, "no-origin"},
		{"no explanation", verified(t, true), func(p *PromoteConstraint) { p.Explanation = "" }, human, "no-explanation"},
		{"missing", Constraint{}, func(*PromoteConstraint) {}, human, "not-found"},
	}
	for _, c := range cases {
		cmd := ok
		c.mod(&cmd)
		evs, err := c.state.Decide(cmd, dctx(c.actor))
		if got := code(t, err); got != c.want {
			t.Errorf("%s: got %q want %q (%v)", c.name, got, c.want, err)
			continue
		}
		if c.want == "" {
			s := core.Replay(c.state, evs)
			if s.Scope != team || len(s.Origin) == 0 || s.Explanation == "" {
				t.Errorf("%s: after promote %+v", c.name, s)
			}
		}
	}
}

func TestConstraint_DemoteSupersedeRetire(t *testing.T) {
	v := verified(t, true)
	narrower := core.ScopeKey{Org: "acme", Team: "core", Repo: "acme/api", PathGlob: "src/*"}

	if _, err := v.Decide(DemoteConstraint{NewConstraintCmd("c1", ""), team, "too broad"}, dctx(human)); code(t, err) != "not-narrower" {
		t.Errorf("demote wider: %v", err)
	}
	if _, err := v.Decide(DemoteConstraint{NewConstraintCmd("c1", ""), narrower, ""}, dctx(human)); code(t, err) != "no-reason" {
		t.Errorf("demote no reason: %v", err)
	}
	evs, err := v.Decide(DemoteConstraint{NewConstraintCmd("c1", ""), narrower, "only billing"}, dctx(human))
	if err != nil {
		t.Fatal(err)
	}
	if s := core.Replay(v, evs); s.Scope != narrower {
		t.Errorf("after demote %+v", s)
	}

	if _, err := v.Decide(SupersedeConstraint{NewConstraintCmd("c1", ""), "c1"}, dctx(human)); code(t, err) != "invalid" {
		t.Errorf("supersede self: %v", err)
	}
	evs, err = v.Decide(SupersedeConstraint{NewConstraintCmd("c1", ""), "c2"}, dctx(human))
	if err != nil {
		t.Fatal(err)
	}
	s := core.Replay(v, evs)
	if s.State != StateRetired || s.SupersededBy != "c2" {
		t.Errorf("after supersede %+v", s)
	}
	if _, err := s.Decide(RetireConstraint{NewConstraintCmd("c1", ""), "x"}, dctx(human)); code(t, err) != "bad-state" {
		t.Errorf("retire retired: %v", err)
	}
	if _, err := s.Decide(DemoteConstraint{NewConstraintCmd("c1", ""), narrower, "r"}, dctx(human)); code(t, err) != "bad-state" {
		t.Errorf("demote retired: %v", err)
	}

	evs, err = v.Decide(RetireConstraint{NewConstraintCmd("c1", ""), "obsolete"}, dctx(agent))
	if err != nil {
		t.Fatal(err)
	}
	if core.Replay(v, evs).State != StateRetired {
		t.Error("retire")
	}
	if _, err := v.Decide(bogusCmd{}, dctx(human)); code(t, err) != "unknown-command" {
		t.Errorf("unknown: %v", err)
	}
}

type bogusCmd struct{}

func (bogusCmd) Kind() string           { return "Bogus" }
func (bogusCmd) Stream() string         { return "x" }
func (bogusCmd) IdempotencyKey() string { return "" }
