package supply

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/young1ll/keelage/internal/core"
)

// FileOp is one change a renderer wants on disk. The adapter applies it
// against the manifest (no-op when unchanged); the renderer never writes.
type FileOp struct {
	Path    string `json:"path"` // repo-relative
	Content string `json:"content,omitempty"`
	Delete  bool   `json:"delete,omitempty"`
	// Managed is true when only the managed block inside Path is ours; the
	// rest of the file belongs to the user and is never touched.
	Managed bool   `json:"managed,omitempty"`
	BlockID string `json:"block_id,omitempty"`
}

// DecisionFact is a decision rendered for a tool.
type DecisionFact struct {
	ID    core.ID
	Title string
	State string
	Path  string // source file in the repo, if imported
}

// RenderInput is the resolved context for one repository and tool.
type RenderInput struct {
	Repo        string
	Tool        string
	Constraints []ConstraintFact // in force, widest first; excludes ones sourced from this repo's own files
	Decisions   []DecisionFact
	Anchors     []AnchorFact // stale/review anchors worth a warning
}

const (
	// ContextDir is where generated context lives (gitignored).
	ContextDir = ".keelage/context"
	beginTag   = "<!-- keelage:begin "
	endTag     = "<!-- keelage:end -->"
)

var blockRe = regexp.MustCompile(`(?s)\n?<!-- keelage:begin (\S+) (\S+) -->\n.*?<!-- keelage:end -->\n?`)

// BlockHash hashes a managed block body (what the adapter compares to
// detect divergence).
func BlockHash(body string) string {
	h := sha256.Sum256([]byte(body))
	return hex.EncodeToString(h[:8])
}

// ManagedBlock wraps body in the begin/end markers.
func ManagedBlock(id, body string) string {
	return beginTag + id + " " + BlockHash(body) + " -->\n" + body + "\n" + endTag
}

// FindBlock returns the managed block with id in content, if present:
// its recorded hash and body.
func FindBlock(content, id string) (hash, body string, ok bool) {
	for _, m := range blockRe.FindAllStringSubmatch(content, -1) {
		if m[1] != id {
			continue
		}
		full := m[0]
		start := strings.Index(full, "-->\n") + 4
		end := strings.LastIndex(full, "\n"+endTag)
		if start < 4 || end < start {
			return m[2], "", true
		}
		return m[2], full[start:end], true
	}
	return "", "", false
}

// UpsertBlock replaces the block with id, or appends one. Text outside the
// block is preserved byte for byte.
func UpsertBlock(content, id, body string) string {
	block := ManagedBlock(id, body)
	replaced := false
	out := blockRe.ReplaceAllStringFunc(content, func(m string) string {
		sub := blockRe.FindStringSubmatch(m)
		if sub[1] != id || replaced {
			return m
		}
		replaced = true
		lead := ""
		if strings.HasPrefix(m, "\n") {
			lead = "\n"
		}
		trail := ""
		if strings.HasSuffix(m, "\n") {
			trail = "\n"
		}
		return lead + block + trail
	})
	if replaced {
		return out
	}
	if content == "" {
		return block + "\n"
	}
	if !strings.HasSuffix(content, "\n") {
		content += "\n"
	}
	return content + "\n" + block + "\n"
}

// RemoveBlock deletes the block with id; the rest is untouched. ok reports
// whether a block was removed.
func RemoveBlock(content, id string) (string, bool) {
	removed := false
	out := blockRe.ReplaceAllStringFunc(content, func(m string) string {
		sub := blockRe.FindStringSubmatch(m)
		if sub[1] != id || removed {
			return m
		}
		removed = true
		if strings.HasPrefix(m, "\n") && strings.HasSuffix(m, "\n") {
			return "\n"
		}
		return ""
	})
	if removed {
		out = strings.TrimRight(out, "\n")
		if out != "" {
			out += "\n"
		}
	}
	return out, removed
}

// PointerBlockID is the managed block that imports the generated context.
const PointerBlockID = "context"

// RenderClaudeCode renders the context for Claude Code (patterns §5.2
// "pointer split"): the generated body goes to
// .keelage/context/claude-code/context.md, and CLAUDE.md gets one managed
// block with an @import line. Pure and deterministic.
func RenderClaudeCode(in RenderInput) []FileOp {
	body := renderContextMarkdown(in)
	contextPath := ContextDir + "/claude-code/context.md"
	return []FileOp{
		{Path: contextPath, Content: body},
		{Path: "CLAUDE.md", Managed: true, BlockID: PointerBlockID, Content: "@" + contextPath},
	}
}

func renderContextMarkdown(in RenderInput) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# keelage context — %s\n\n", in.Repo)
	b.WriteString("Generated by keelage from the charter in force for this repository. Do not edit: run `keelage init` to refresh. ")
	b.WriteString("Statements here are project facts.\n")
	if len(in.Constraints) > 0 {
		b.WriteString("\n## Constraints in force\n")
		cs := append([]ConstraintFact(nil), in.Constraints...)
		sort.SliceStable(cs, func(i, j int) bool {
			wi, wj := cs[i].Scope.Width(), cs[j].Scope.Width()
			if wi != wj {
				return wi > wj
			}
			return cs[i].ID < cs[j].ID
		})
		for _, c := range cs {
			fmt.Fprintf(&b, "\n- **%s** (%s, %s): %s", c.Kind, c.State, scopeLabel(c.Scope), strings.TrimSpace(c.Body))
			if c.Explanation != "" {
				fmt.Fprintf(&b, " — %s", strings.TrimSpace(c.Explanation))
			}
			if len(c.Anchors) > 0 {
				fmt.Fprintf(&b, " · anchors: %s", strings.Join(c.Anchors, ", "))
			}
			if c.DenyEdit {
				b.WriteString(" · agents do not edit here")
			}
		}
		b.WriteString("\n")
	}
	if len(in.Decisions) > 0 {
		b.WriteString("\n## Decisions\n")
		ds := append([]DecisionFact(nil), in.Decisions...)
		sort.Slice(ds, func(i, j int) bool { return ds[i].Title < ds[j].Title })
		for _, d := range ds {
			fmt.Fprintf(&b, "\n- %s (%s)", d.Title, d.State)
			if d.Path != "" {
				fmt.Fprintf(&b, " — see %s", d.Path)
			}
		}
		b.WriteString("\n")
	}
	if len(in.Anchors) > 0 {
		b.WriteString("\n## Anchors needing attention\n")
		as := append([]AnchorFact(nil), in.Anchors...)
		sort.Slice(as, func(i, j int) bool { return as[i].Key < as[j].Key })
		for _, a := range as {
			fmt.Fprintf(&b, "\n- %s is %s", a.Key, a.State)
			if a.MovedTo != "" {
				fmt.Fprintf(&b, " (moved to %s)", a.MovedTo)
			}
		}
		b.WriteString("\n")
	}
	b.WriteString("\nBefore editing a symbol listed above, call `mcp__keelage__what_touches` with its anchor.\n")
	return b.String()
}
